apiVersion: v1
kind: PersistentVolume
metadata:
  name: criticalvolume
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /criticalvolume
    server: 10.74.102.146  # GCP project:turbiniang-k8s
