apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbinia-server
  labels:
    app: turbinia-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbinia-server
  template:
    metadata:
      annotations:
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
      labels:
        app: turbinia-server
    spec:
      initContainers:
        - name: init-filestore
          image: busybox:1.28
          command: ["sh", "-c", "chmod go+w /mnt/criticalvolume"]
          volumeMounts:
            - mountPath: "/mnt/criticalvolume"
              name: criticalvolume
      containers:
        - name: server
          #image: us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-ng-server-dev:latest
          image: wyassine/turbinia-server-dev
          env:
            - name: TURBINIA_CONF
              valueFrom:
                configMapKeyRef:
                  name: turbinia-config
                  key: TURBINIA_CONF
            - name: TURBINIA_EXTRA_ARGS
              value: "-d"
          volumeMounts:
            - mountPath: /mnt/criticalvolume
              name: criticalvolume
          ports:
            - containerPort: 9200
      volumes:
        - name: criticalvolume
          persistentVolumeClaim:
            claimName: criticalvolume-claim
            readOnly: false